#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_scalar_block_layout : enable

#include "descriptors.glsl"
#include "../common/viewport.glsl"

layout(location = 0) rayPayloadEXT PrimaryHitPayload prd;

layout(binding = 6, set = 0, rgba8) uniform image2D output;

void main() {
    prd.output = vec3(0);
    prd.cozw = vec2(0, 0);
    traceViewportPixelRay();
    imageStore(output, ivec2(gl_LaunchIDEXT.xy), prd.result);
}
