[package]
name = "wilds"
version = "0.1.0"
authors = ["Zakarum <zakarumych@ya.ru>"]
edition = "2018"

[features]
# Graphics backend
vulkan = ["illume-erupt"]

# Image formats support

[dependencies]
# Assets
goods = { version = "0.5", features = ["fs", "tokio-spawn"], path = "../../goods" }
gltf = "0.15"

# Physics
ncollide3d = "0.23"

# Graphics
illume = { path = "../illume", features = ["ultraviolet", "serde-1"] }
illume-erupt = { path = "../erupt", optional = true, features = ["shader-compiler"] }
genmesh = { version = "0.6", optional = true }
palette = { version = "0.5", default-features = false, features = ["std"] }
image = { version = "0.23", features = ["png"] }
png = "0.16"

# ECS
hecs = "0.2"

# Linear algebra
nalgebra = "0.21"
ultraviolet = "0.4"

# Windowing
winit = "0.22" # "0.22.2"

# Low-Level
bytemuck = "1.2"
byteorder = "1.3"
bumpalo = { version = "3.4", features = ["collections"] }

# Error handling
eyre = "0.6"
color-eyre = "0.5"
thiserror = "1.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
ron = "0.6"

# Logs and traces
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.2", features = ["fmt"] }

# Support
fastbitset = { path = "../fastbitset" }
cfg-if = "0.1"
futures = "0.3"
lazy_static = "1.4"
flume = { version = "0.7", features = ["async"] }
ordered-float = "2.0"
hibitset = "0.6"
num-traits = "0.2"
smallvec = "1.4"
bitflags = "1.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "0.2", features = ["macros", "rt-threaded", "blocking"] }
